on:
  push:
    branches: [ main, stagging, dev ]
  pull_request:
    branches: [ main, stagging, dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 21.x
        uses: actions/setup-node@v2
        with:
          node-version: '21.x'
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test